// ----------------------------- MySQL -----------------------------

// ======================
// ENUM DEFINITIONS
// ======================

Enum user_role {
  admin        // Quản trị hệ thống
  doctor       // Bác sĩ
  patient      // Bệnh nhân
}

Enum user_status {
  active       // Tài khoản đang hoạt động
  locked       // Tài khoản bị khóa
  pending      // Tài khoản mới tạo (là patient chưa điền thông tin: isProfileComplete)
}

Enum gender_type {
  male         // Nam
  female       // Nữ
  other        // Khác
}

Enum patient_condition_level {
  stable          // Ổn định 
  monitoring      // Cần theo dõi 
  critical        // Nguy hiểm 
}

Enum patient_doctor_role {
  primary        // Bác sĩ chính (chịu trách nhiệm)
  consultant     // Bác sĩ tư vấn / hỗ trợ
  on_call        // Bác sĩ trực / xử lý khẩn cấp
}

Enum alert_severity {
  low          // Mức độ cảnh báo thấp
  medium       // Mức độ cảnh báo trung bình
  critical     // Cảnh báo nghiêm trọng
}

Enum appointment_status {
  pending      // Chờ bác sĩ xác nhận lịch hẹn
  confirmed    // Lịch hẹn đã được xác nhận
  completed    // Buổi khám đã hoàn thành
  cancelled    // Lịch hẹn bị hủy
}

Enum appointment_type {
  online       // Lịch hẹn trực tuyến
  offline      // Lịch hẹn trực tiếp
}

Enum call_status {
  missed       // Cuộc gọi nhỡ
  rejected     // Cuộc gọi bị từ chối
  completed    // Cuộc gọi thành công
}

Enum health_status {
  normal       // Tình trạng sức khỏe bình thường
  warning      // Có dấu hiệu bất thường
  critical     // Nguy hiểm, cần can thiệp y tế
}

Enum noti_type {
  alert
  appointment
  message
}

// ======================
// USERS & AUTH
// ======================

Table users {
  id int [pk, increment]
  full_name varchar [not null]                // Họ và tên
  email varchar [unique, not null]            // Email đăng nhập
  password varchar [not null]                 // Mật khẩu
  role user_role [default: 'patient']         // Phân quyền
  avatar varchar                              // Ảnh đại diện
  phone_number varchar                        // Số điện thoại

  status user_status [default: 'pending']      // Trạng thái tài khoản
  last_login_at datetime                      // Thời điểm đăng nhập gần nhất

  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table refresh_tokens {
  id int [pk, increment]
  token varchar [not null]
  user_id int [not null, ref: > users.id]     // User sở hữu token
  expires_at datetime [not null]              // Thời điểm hết hạn
  is_revoked boolean [default: false]         // Token đã bị thu hồi hay chưa
  device_info varchar                         // Thông tin thiết bị đăng nhập

  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

// ======================
// MEDICAL ROLES
// ======================

// Chuyên khoa
Table specialties {
  id int [pk, increment]
  name varchar [not null]                  // Tên chuyên khoa (VD: Tim mạch, Nội tiết)
  description text                         // Mô tả chuyên khoa
  image_url varchar                        // Đường dẫn file
  
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table doctors {
  user_id int [pk, ref: - users.id]

  specialty_id int [ref: > specialties.id]    // Chuyên khoa

  degree varchar                              // Bằng cấp
  experience_years int                        // Số năm kinh nghiệm
  bio text                                    // Giới thiệu ngắn về bác sĩ
  address varchar                             // Địa chỉ bệnh viện

  created_at timestamp [default: `now()`]     
  updated_at timestamp [default: `now()`]      
}

// Giờ bác sĩ làm việc 
Table doctor_working_hours {
  id int [pk, increment]
  doctor_id int [ref: > doctors.user_id] 
  
  day_of_week int [not null, note: '0: Chủ nhật, 1: Thứ 2, ..., 6: Thứ 7']
  start_time time [not null]               // Giờ bắt đầu ca (VD: '08:00:00')
  end_time time [not null]                 // Giờ kết thúc ca (VD: '12:00:00')
  
  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`]
}

// Ngày nghỉ/bận của bác sĩ
Table doctor_off_schedules {
  id int [pk, increment]
  doctor_id int [ref: > doctors.user_id]
  
  off_date date [not null]                 // Ngày nghỉ/bận (VD: '2026-03-15')
  start_time time                          // Từ mấy giờ (Để null nếu nghỉ cả ngày)
  end_time time                            // Đến mấy giờ (Để null nếu nghỉ cả ngày)
  reason varchar                           // Lý do (Họp, nghỉ phép...)
  
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table patients {
  user_id int [pk, ref: - users.id]      

  date_of_birth date                      // Ngày sinh
  gender gender_type                      // Giới tính
  blood_type varchar                      // Nhóm máu
  height float [note: 'cm']               // Chiều cao (cm)
  weight float [note: 'kg']               // Cân nặng (kg)
  medical_history text                    // Tiền sử bệnh
  address varchar                         // Địa chỉ

  current_health_status patient_condition_level [default: 'stable']     // Dùng để hiển thị Label màu (Trạng thái)
  current_issue varchar                                                 // Dùng để hiển thị text "Tình trạng" (VD: "Huyết áp cao", "Nhịp tim nhanh")
  last_alert_at datetime                                                // Thời điểm có cảnh báo cuối cùng

  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`] 
}

Table patient_doctors {
  patient_id int [ref: > patients.user_id]  
  doctor_id int [ref: > doctors.user_id]   

  role patient_doctor_role [not null]
  assigned_at datetime                      // Thời điểm phân công

  primary key (patient_id, doctor_id)       // Quan hệ nhiều-nhiều
}

// Lịch hẹn
Table appointments {                        
  id int [pk, increment]                  

  patient_id int [ref: > patients.user_id]  // Bệnh nhân
  doctor_id int [ref: > doctors.user_id]    // Bác sĩ

  scheduled_at datetime [not null]          // Thời gian hẹn
  actual_ended_at datetime [null]           // Hệ thống tự update khi bác sĩ bấm "Kết thúc ca"
  duration_minutes int [default: 30, note: '30 hoặc 60 phút']   // Dùng duration + scheduled_at để tính toán khoảng thời gian bị chiếm, hỗ trợ bệnh nhân khác đặt ca khám

  status appointment_status [default: 'pending']  // Trạng thái lịch hẹn
  type appointment_type [default: 'online']       // Loại lịch hẹn (online, trực tiếp)
  meeting_link varchar                   // Link khám online
  reason text                            // Lý do khám
  cancel_reason text                     // Lý do hủy

  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`] 
}

// ======================
// DEVICES & IOT
// ======================

Table devices {
  id varchar [pk]                                   // Device ID
  name varchar                                      // Tên thiết bị
  is_online boolean                                 // online / offline

  is_assigned boolean                               // Đã kết nối với bệnh nhân nào chưa
  assigned_to int [ref: > patients.user_id, null]   // Thiết bị gắn với bệnh nhân nào

  created_at timestamp [default: `now()`]   
  updated_at timestamp [default: `now()`]   
}

// ======================
// ALERTS & AI
// ======================

Table alerts {
  id int [pk, increment]                    

  patient_id int [not null, ref: > patients.user_id]        // Bệnh nhân liên quan
  prediction_id int [ref: > health_predictions.id, null]    // Kết quả AI sinh cảnh báo
  device_id varchar [ref: > devices.device_id, null]        // Thiết bị nào

  type varchar                                  // Loại chỉ số (bpm, spo2)
  value float                                   // Giá trị đo được
  message varchar                               // Nội dung cảnh báo
  severity alert_severity [default: 'medium']   // Mức độ nghiêm trọng

  source varchar                                      // Nguồn cảnh báo: threshold | ml | manual
  is_resolved boolean [default: false]                // Đã xử lý hay chưa
  resolved_at datetime                                // Thời điểm xử lý
  resolved_by int [ref: > doctors.user_id, null]      // Xử lý bởi

  created_at timestamp [default: `now()`]  
  updated_at timestamp [default: `now()`]  
}

// Bảng trung gian cảnh báo cho bác sĩ nào
Table alert_recipients {                        
  alert_id int [ref: > alerts.id]                       // Cảnh báo
  doctor_id int [ref: > doctors.user_id]                // Bác sĩ nhận cảnh báo từ bệnh nhân

  is_read boolean [default: false]                      // Xem chưa
  is_acknowledged boolean [default: false]              // Xử lý chưa

  delivered_at datetime [not null]                      // Thời điểm cảnh báo 
  read_at datetime                                      // Thời điểm xem  
  acknowledged_at datetime                              // Thời điểm xử lý 

  primary key (alert_id, doctor_id)
}

Table health_predictions {
  id int [pk, increment]                  

  patient_id int [ref: > patients.user_id]  // Bệnh nhân được dự đoán

  predicted_status health_status            // Trạng thái sức khỏe dự đoán
  confidence float                          // Độ tin cậy (0–1)

  model_version varchar                     // Phiên bản mô hình ML
  input_window int                          // Số mẫu đầu vào (window size)

  created_at datetime [default: `now()`]    
}

// ======================
// MEDICAL DATA
// ======================

// Hồ sơ khám bệnh 
Table medical_records {                     
  id int [pk, increment]                 

  appointment_id int [ref: > appointments.id] // Ca khám nào
  patient_id int [ref: > patients.user_id]    // Bệnh nhân
  doctor_id int [ref: > doctors.user_id]      // Bác sĩ khám

  symptoms text                             // Triệu chứng
  diagnosis text                            // Chẩn đoán

  treatment_plan text                       // Hướng điều trị
  prescription json                         // Đơn thuốc
  notes text                                // Ghi chú thêm

  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`] 
}

// File đính kèm
Table medical_attachments {             
  id int [pk, increment]                  

  medical_record_id int [ref: > medical_records.id]   // Hồ sơ liên quan

  file_name varchar                     // Tên file
  file_url varchar                      // Đường dẫn file
  file_type varchar                     // Loại file: image | pdf
  uploaded_at datetime                  // Thời điểm upload
}

// ======================
// TELEMEDICINE
// ======================

Table chat_messages {
  id int [pk, increment]                 

  sender_id int [ref: > users.id]         // Người gửi
  receiver_id int [ref: > users.id]       // Người nhận

  message text                            // Nội dung tin nhắn
  attachment_url varchar                  // File/ảnh đính kèm
  is_read boolean [default: false]        // Đã đọc hay chưa

  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`] 
}

Table call_logs {
  id int [pk, increment]                   

  caller_id int [ref: > users.id]           // Người gọi
  receiver_id int [ref: > users.id]         // Người nhận

  start_time datetime                       // Thời điểm bắt đầu
  end_time datetime                         // Thời điểm kết thúc
  duration_seconds int                      // Thời lượng cuộc gọi (giây)

  status call_status [default: 'missed']    // Trạng thái cuộc gọi

  created_at timestamp [default: `now()`] 
  updated_at timestamp [default: `now()`]
}

Table notifications {
  id int [pk, increment]

  user_id int [not null, ref: > users.id]     // thông báo cho ai

  type noti_type [not null]         // alert | appointment | message

  title varchar
  content text

  reference_id int                // alert_id, appointment_id, message_id

  sender_id int [ref: > users.id, null]       // doctor_id, patient_id khi nhận chat, appointment

  is_read boolean [default: false]
  read_at datetime

  created_at timestamp [default: `now()`]
}

// ----------------------------- MongoDB -----------------------------
// const ECGRawSchema = new mongoose.Schema(
//   {
//     device_id: { type: String, required: true, index: true },
//     patient_id: { type: Number, required: true, index: true },
//     bucket_start_time: { type: Date, required: true, index: true },
//     count: { type: Number, default: 0 },
//     samples: [
//       {
//         ts: { type: Date }, // Timestamp của mẫu ECG
//         val: [Number], // Mảng 187 điểm ECG
//         status: String // 'NORMAL', 'DANGER'
//       }
//     ]
//   },
//   {
//     timestamps: true
//   }
// )
//
// const HealthMetricSchema = new mongoose.Schema(
//   {
//     timestamp: { type: Date, required: true },
//     metadata: {
//       patient_id: Number,
//       device_id: String
//     },
//     bpm: Number,
//     spo2: Number,
//     hrv: Number,
//     status: String // 'NORMAL', 'DANGER'
//   },
//   {
//     timeseries: {
//       timeField: 'timestamp',
//       metaField: 'metadata',
//       granularity: 'seconds'
//     },
//     expireAfterSeconds: 2592000 // Tự động xóa sau 30 ngày (TTL Index)
//   }
// )
//
// const MessageSchema = new mongoose.Schema(
//   {
//     conversation_id: {
//       type: mongoose.Schema.Types.ObjectId,
//       ref: 'Conversation',
//       required: true
//     },
//     sender_id: {
//       type: mongoose.Schema.Types.Mixed, // user_id từ SQL hoặc 'system'
//       required: true
//     },
//     type: {
//       type: String,
//       enum: ['text', 'image', 'file', 'system_alert'],
//       default: 'text'
//     },
//     content: {
//       text: { type: String },

//       // Dùng cho type 'image' hoặc 'file'
//       file_url: { type: String },
//       file_name: { type: String },

//       // Dùng cho type 'system_alert' (cảnh báo từ IoT/AI)
//       alert_id: { type: Number },
//       severity: { type: String, enum: ['low', 'medium', 'high', 'critical'] },
//       value: { type: String }
//     },
//     status: {
//       type: String,
//       enum: ['sent', 'delivered', 'read'],
//       default: 'sent'
//     }
//   },
//   {
//     timestamps: { createdAt: 'created_at', updatedAt: false }
//   }
// )
//
// const ConversationSchema = new mongoose.Schema(
//   {
//     // Mảng chứa user_id (từ SQL) của Bác sĩ và Bệnh nhân
//     participants: {
//       type: [Number],
//       required: true,
//       validate: {
//         validator: (v) => v.length === 2,
//         message: 'Conversation phải có đúng 2 participants'
//       }
//     },

//     // Nhúng trực tiếp tin nhắn cuối để hiển thị preview
//     last_message: {
//       message_id: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: 'Message'
//       },
//       sender_id: { type: mongoose.Schema.Types.Mixed }, // Number or 'system'
//       type: {
//         type: String,
//         enum: ['text', 'image', 'file', 'system_alert']
//       },
//       content: { type: String },
//       created_at: { type: Date }
//     },

//     // Đếm tin nhắn chưa đọc của từng người – key là user_id (string), value là số đếm
//     unread_counts: {
//       type: Map,
//       of: Number,
//       default: {}
//     }
//   },
//   {
//     timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
//   }
// )